version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1870:4200"

  backend:
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
